import Navbar from "@/components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Next Course",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Navbar />
        {children}

      </body>
    </html>
  );
}
